import React, {useState} from 'react';
import 'tailwindcss/tailwind.css'
import Link from "next/link"
import Head from 'next/head'
function useStatePage() {
    // useState return array with value and setter for that value, receives 
    // an optional argument with initial state.
    // const [value, setValue] = useState(initialValue);
    const [state, setState] = useState({
        count: 4,
        color: "blue"
    });
    const [clases, setClases] = useState("bg-blue-600")

    const count = state.count;
    const color = state.color;
    const colors = ["blue", "indigo", "green", "yellow"];

    // Decrement Count function
    function decrementCount(){
        // Incorrect, this replace full object wiht {count: value} so 
        // blue attribute will dissapear
        // setState(prevState => {
        //     return { count : prevState.count - 1}
        // });

        // Correct way
        setState(prevState => {
            return {...prevState, count : prevState.count - 1}
        });
    }

    // Increment Coutn Function
    function incrementCount(){
         // Incorrect, this replace full object wiht {count: value} so 
        // blue attribute will dissapear
        // setState(prevState => {
        //     return { count : prevState.count + 1}
        // });

        // Correct way
        setState(prevState => {
            return {...prevState, count : prevState.count + 1}
        });
    }function decrementColor(){
        setState(prevState => {
            const i = 0;
            const total = 4;
            for (i = 0; total; i++){
                if (prevState.color == colors[i]){
                    i=i-1;
                    if (i == -1){
                        let fondo = clases[0];
                        fondo = "bg-yellow-400";
                        setClases(fondo);
                        return {...prevState, color : colors[3]}
                    }else{
                        let fondo = clases[0];
                        fondo = "bg-"+colors[i]+"-400";
                        setClases([fondo]);
                        return {...prevState, color : colors[i]}
                    }
                    
                }
            }
            //return {...prevState, color : colors[2]}
        });
    }

    // Increment Coutn Function
    function incrementColor(){
        setState(prevState => {
            const i = 0;
            const total = 4;
            for (i = 0; total; i++){
                if (prevState.color == colors[i]){
                    i=i+1;
                    if (i == 4){
                        let fondo = clases[0];
                        fondo = "bg-blue-600";
                        setClases(fondo);
                        return {...prevState, color : colors[0]}
                    }else{
                        let fondo = clases[0];
                        fondo = "bg-"+colors[i]+"-400";
                        setClases([fondo]);
                        return {...prevState, color : colors[i]}
                    }
                    
                }
            }
            //return {...prevState, color : colors[2]}
        });
    }

    return (
        <>
        <Head>
            <title>Calculos 📝</title>
            <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="central">
            <div className="cabecera">
                <h1 className="tituloHola">Esta es la página de Calculos</h1>
            </div>
            <div className="botones">
                <button className="boton">
                    <Link href="/"><a className="botonPrincipal">Volver!</a></Link>
                </button>
            </div>      
        </main>
            <h1 className="nombreFunciones">Cambiar número</h1>
            <div className="botonesCentral">
                <button id="botonesFunciones" className={clases} onClick={decrementCount}>-</button>
                <span className="text-2xl mx-4">{count}</span>
                <span className="text-2xl mx-4">{color}</span>
                <button id="botonesFunciones" className={clases} onClick={incrementCount}>+</button>
            </div>
            <h1 className="nombreFunciones">Cambiar color</h1>
            <div className="botonesCentral">
                
                <button id="botonesFunciones" className={clases} onClick={decrementColor}>-</button>
                <span className="text-2xl mx-4">{count}</span>
                <span className="text-2xl mx-4">{color}</span>
                <button id="botonesFunciones" className={clases} onClick={incrementColor}>+</button>
            </div>
        </>
    )
}

export default useStatePage;