import Head from 'next/head'
import Image from 'next/image'
import 'tailwindcss/tailwind.css'
import Link from "next/link"

export default function Home() {
  return (
  <div className="container">
    <Head>
      <title>Prueba 🚀</title>
      <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="central">
      <div className="cabecera">
          <h1 className="titulo">
            Prueba de <Link href="https://nextjs.org"><a>Next.js!</a></Link>
          </h1>
      </div>
    
        <div className="botones">
          
          <button className="boton">
            <Link href="/universidad"><a className="botonPrincipal">Universidad!</a></Link>
          </button>
          <button className="boton">
            <Link href="/numeros"><a className="botonPrincipal">Numeros!</a></Link>
          </button>
          <button className="boton">
            <Link href="/lista"><a className="botonPrincipal">Lista!</a></Link>
          </button>
          <button className="boton">
            <Link href="/nueva"><a className="botonPrincipal">Nueva!</a></Link>
          </button>
        </div>
    </main>
      <footer>
        <img src="https://www-europe.nissan-cdn.net/content/dam/Nissan/nissan_europe/vehicles/gt-r/r35/2_minor_change/overview/19TDIEULHD_GT-R_002.jpg.ximg.l_full_m.smart.jpg" className="coche"></img>
      </footer>
  </div> 
  )
}
