import React, {useState} from 'react';
import 'tailwindcss/tailwind.css'
import Link from "next/link"
import Head from 'next/head'

function useStatePage() {
    // useState return array with value and setter for that value, receives 
    // an optional argument with initial state.
    // const [value, setValue] = useState(initialValue);
    const [count, setCount] = useState(4);
    const [clases, setClases] = useState(["btn", "bg-green-400", "mx-4"])

    // Decrement Count function
    function decrementCount(){
        // Not perfect way
        // setCount(count - 1);
        // Recomended way
        setCount(prevCount => prevCount - 1);
        let color = clases[1];
        color = "bg-red-400";
        setClases(["btn",color,"mx-4"]);
    }

    // Increment Coutn Function
    function incrementCount(){
         // Not perfect way
        // setCount(count + 1);
        // Recomended way
        setCount(prevCount => prevCount + 1);
        let color = clases[1];
        color = "bg-gray-400";
        setClases(["btn",color,"mx-4"]);
    }
    function multiplicarCount(){
        // Not perfect way
       // setCount(count + 1);
       // Recomended way
       setCount(prevCount => prevCount * prevCount);
       let color = clases[1];
        color = "bg-purple-400";
        setClases(["btn",color,"mx-4"]);
   }
    function dividirCount(){
    // Not perfect way
    // setCount(count + 1);
    // Recomended way
    setCount(prevCount => prevCount / 2);
    let color = clases[1];
    color = "bg-yellow-400";
    setClases(["btn",color,"mx-4"]);
    }
    function cambiarColor(){
        let color = clases[1];
        if(color === "bg-green-400") color = "bg-yellow-400";
        else if(color === "bg-yellow-400") color = "bg-red-400";
        else if(color === "bg-red-400") color = "bg-blue-400";
        else if(color === "bg-blue-400") color = "bg-green-400";
        else color = "bg-blue-400";
        setClases(["btn",color,"mx-4"]);
    }

    return (
        <>
        <Head>
            <title>Numeros ➕</title>
            <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="central">
            <div className="cabecera">
                <h1 className="tituloHola">Esta es la página de Calculos</h1>
            </div>
            <div className="botones">
                <button className="boton">
                    <Link href="/"><a className="botonPrincipal">Volver!</a></Link>
                </button>
            </div>      
        </main>
            <div className="botonesCentral">
                <button className={clases.join(" ")} id="botonesFunciones" onClick={decrementCount}>-</button>
                <span className="text-2xl mx-4">{count}</span>
                <button className={clases.join(" ")} id="botonesFunciones" onClick={incrementCount}>+</button>
                
                <button className={clases.join(" ")} id="botonesFunciones" onClick={multiplicarCount}>*</button>
                
                <button className={clases.join(" ")} id="botonesFunciones" onClick={dividirCount}>/</button>
                <button className="botonColor" onClick={cambiarColor}>Color</button>
            </div>
            
        </>
    )
}

export default useStatePage;